---
kind: pipeline
name: node8-arm64v8

platform:
  os: linux
  arch: arm64

steps:
  - name: build
    image: arm64v8/node:10.15.3
    volumes:
      - name: vendor
        path: /tmp/vendor
    commands:
      - export SKIP_SASS_BINARY_DOWNLOAD_FOR_CI="true"
      - env
      - node -v
      - npm -v
      - gcc --version
      - g++ --version
      - node -p process.versions
      - node -p process.arch
      - node -p process.platform
      - node -p process.config.variables
      - uname -m
      - npm install --unsafe-perm
      - npm test
      - node scripts/release.js
      # - cp -R /drone/src/vendor /tmp
      # - ls -lsa /tmp/vendor
volumes:
  - name: vendor
    temp: {}
---
kind: pipeline
name: node8-arm32v7

platform:
  os: linux
  arch: arm

steps:
  - name: build
    image: arm32v7/node:10
    volumes:
      - name: vendor
        path: /tmp/vendor
    commands:
      - export SKIP_SASS_BINARY_DOWNLOAD_FOR_CI="true"
      - env
      - node -v
      - npm -v
      - gcc --version
      - g++ --version
      - node -p process.versions
      - node -p process.arch
      - node -p process.platform
      - node -p process.config.variables
      - uname -m
      # - npm install --unsafe-perm
      # - npm test
      # - cp -R /drone/src/vendor /tmp
      # - ls -lsa /tmp/vendor
volumes:
  - name: vendor
    temp: {}


